In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv(r"C:\Users\PC\Desktop\Crop Prediction Dataset (U).csv")

In [3]:
df.head(2)

,Record_ID,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Rainfall_Category,Fertilizer_per_Area,Pesticide_per_Area,Yield_Category,Year_Group
0,1,Arecanut,1997,Whole Year,Assam,73814.0,56708.0,2051.4,7024878.38,22882.34,0.796087,0.768255,High,95.17,0.31,Low,1997-2000
1,2,Arhar/Tur,1997,Kharif,Assam,6637.0,4685.0,2051.4,631643.29,2057.47,0.710435,0.705891,High,95.17,0.31,Low,1997-2000

## python questions

In [4]:
# 1  Identify how many columns contain null values, and for each such column, determine the total number of null values. 
df.isnull().sum()

Record_ID                 0
Crop                      0
Crop_Year                 0
Season                    0
State                     0
Area                   1378
Production             1378
Annual_Rainfall         110
Fertilizer              563
Pesticide                 0
Yield                  1181
Production_per_Area    1575
Rainfall_Category         0
Fertilizer_per_Area       0
Pesticide_per_Area        0
Yield_Category            0
Year_Group                0
dtype: int64

In [5]:
# 2. Check whether the columns Area and Production contain any null values. If null values are present, first examine whether these columns contain outliers. If outliers exist, fill the null values using an appropriate technique. Ensure that no decimal values are allowed in the Area column.

In [6]:
df.describe()

,Record_ID,Crop_Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Fertilizer_per_Area,Pesticide_per_Area
count,19689.000000,19689.000000,1.831100e+04,1.831100e+04,19579.000000,1.912600e+04,1.968900e+04,18508.000000,18114.000000,19689.000000,19689.000000
mean,9845.000000,2009.127584,1.816562e+05,1.648194e+07,1433.913357,2.406195e+07,4.884835e+04,73.172834,82.978196,137.160208,0.274374
std,5683.869061,6.498099,7.437564e+05,2.639108e+08,817.412943,9.526848e+07,2.132874e+05,837.377629,912.883186,26.200647,0.073284
min,1.000000,1997.000000,5.000000e-01,0.000000e+00,301.300000,5.417000e+01,9.000000e-02,0.000000,0.000000,94.670000,0.090000
25%,4923.000000,2004.000000,1.392000e+03,1.374500e+03,935.600000,1.875406e+05,3.567000e+02,0.580000,0.595518,108.340000,0.220000
50%,9845.000000,2010.000000,9.378000e+03,1.368400e+04,1246.200000,1.224675e+06,2.421900e+03,0.982466,1.032415,144.490000,0.270000
75%,14767.000000,2015.000000,7.537600e+04,1.220810e+05,1633.100000,9.870326e+06,2.004170e+04,2.200000,2.460542,157.910000,0.330000
max,19689.000000,2020.000000,5.080810e+07,6.326000e+09,6552.700000,4.835407e+09,1.575051e+07,21105.000000,21105.000000,193.610000,0.380000

In [7]:
df["Area"]=df["Area"].fillna(df["Area"].median())

In [8]:
df["Production"]=df["Production"].fillna(df["Production"].median())

In [9]:
# 3. It has been observed that the missing values in the  Annual_Rainfall column follow an average rainfall pattern. Fill  the missing values using the average rainfall of the column.  Ensure that the final values are stored as integers (no decimal values allowed).

In [10]:
df["Annual_Rainfall"]=df["Annual_Rainfall"].fillna(df["Annual_Rainfall"].median()).astype(int)

In [11]:
# 4. Determine the maximum and minimum values in the Fertilizer column. Calculate the average of these two values and use this average to fill all missing values. Ensure that the filled values contain at least two decimal places.

maximum=df["Fertilizer"].max()
minimum=df["Fertilizer"].min()

In [12]:
avg=(maximum+ minimum)/2

In [13]:
df["Fertilizer"]=df["Fertilizer"].fillna(avg)

In [14]:
# 5. Analyze whether the Yield column contains outliers. If outliers are present or not, handle the missing values using an appropriate technique and justify your approach.

df.describe()

,Record_ID,Crop_Year,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Fertilizer_per_Area,Pesticide_per_Area
count,19689.000000,19689.000000,1.968900e+04,1.968900e+04,19689.000000,1.968900e+04,1.968900e+04,18508.000000,18114.000000,19689.000000,19689.000000
mean,9845.000000,2009.127584,1.695988e+05,1.532936e+07,1432.390472,9.250728e+07,4.884835e+04,73.172834,82.978196,137.160208,0.274374
std,5683.869061,6.498099,7.186014e+05,2.545421e+08,815.247565,4.098456e+08,2.132874e+05,837.377629,912.883186,26.200647,0.073284
min,1.000000,1997.000000,5.000000e-01,0.000000e+00,301.000000,5.417000e+01,9.000000e-02,0.000000,0.000000,94.670000,0.090000
25%,4923.000000,2004.000000,1.652000e+03,1.622000e+03,940.000000,1.993811e+05,3.567000e+02,0.580000,0.595518,108.340000,0.220000
50%,9845.000000,2010.000000,9.378000e+03,1.368400e+04,1246.000000,1.379919e+06,2.421900e+03,0.982466,1.032415,144.490000,0.270000
75%,14767.000000,2015.000000,6.385400e+04,1.000000e+05,1632.000000,1.204605e+07,2.004170e+04,2.200000,2.460542,157.910000,0.330000
max,19689.000000,2020.000000,5.080810e+07,6.326000e+09,6552.000000,4.835407e+09,1.575051e+07,21105.000000,21105.000000,193.610000,0.380000

In [15]:
df["Yield"]=df["Yield"].fillna(df["Yield"].median())
# i using median method just because it can be usefull in normalization in outlier data

In [16]:
# 6  The Production_per_Area column contains missing values due to data collection gaps.
# 7. Impute the missing values in the Production_per_Area column using a forward fill strategy and store the updated values back in the same column.

In [17]:
df["Production_per_Area"]=df["Production_per_Area"].ffill()

In [18]:
# 8. After completing all the data cleaning, preprocessing, and transformation steps on both datasets (Crop_Production and Climate_Agriculture), split the final cleaned dataset into two separate CSV files and export them according to the following specifications:

In [19]:
df.head(2)

,Record_ID,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Rainfall_Category,Fertilizer_per_Area,Pesticide_per_Area,Yield_Category,Year_Group
0,1,Arecanut,1997,Whole Year,Assam,73814.0,56708.0,2051,7024878.38,22882.34,0.796087,0.768255,High,95.17,0.31,Low,1997-2000
1,2,Arhar/Tur,1997,Kharif,Assam,6637.0,4685.0,2051,631643.29,2057.47,0.710435,0.705891,High,95.17,0.31,Low,1997-2000

In [20]:
data=df.copy()

In [21]:
data1=df.copy()

In [22]:
data.head(2)

,Record_ID,Crop,Crop_Year,Season,State,Area,Production,Annual_Rainfall,Fertilizer,Pesticide,Yield,Production_per_Area,Rainfall_Category,Fertilizer_per_Area,Pesticide_per_Area,Yield_Category,Year_Group
0,1,Arecanut,1997,Whole Year,Assam,73814.0,56708.0,2051,7024878.38,22882.34,0.796087,0.768255,High,95.17,0.31,Low,1997-2000
1,2,Arhar/Tur,1997,Kharif,Assam,6637.0,4685.0,2051,631643.29,2057.47,0.710435,0.705891,High,95.17,0.31,Low,1997-2000

In [23]:
df=df.drop(["Annual_Rainfall","Fertilizer","Pesticide","Rainfall_Category","Fertilizer_per_Area","Pesticide_per_Area","Year_Group"],axis="columns")
data=data.drop(["Crop","Crop_Year","Season","State","Area","Production","Yield","Yield_Category","Production_per_Area","Pesticide_per_Area","Year_Group"],axis="columns")

In [24]:
data.head(2)

,Record_ID,Annual_Rainfall,Fertilizer,Pesticide,Rainfall_Category,Fertilizer_per_Area
0,1,2051,7024878.38,22882.34,High,95.17
1,2,2051,631643.29,2057.47,High,95.17

In [25]:
df.to_csv("Crop_ Production.csv",index=False)

In [26]:
data.to_csv("Climate_Agriculture.csv",index=False)

In [27]:
data1.to_csv("Crop_Yield.csv",index=False)